# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "A client for the MakeOS decentralized code collaboration network"
  homepage "https://makeos.org/"
  version "0.0.32"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/make-os/kit/releases/download/v0.0.32/kit_0.0.32_Darwin_x86_64.tar.gz"
    sha256 "d91b6c1fa4a16ef5914a8a14df11f3399293568ae200b88d8458b0d344d3e2ee"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/make-os/kit/releases/download/v0.0.32/kit_0.0.32_Linux_x86_64.tar.gz"
    sha256 "63f3c9bdcb42d5e35962f08b1b88c4f39c69453d20c6cac0724553b469465b60"
  end

  depends_on "git"

  def install
    bin.install "kit"
  end

  test do
    system "#{bin}/kit --version"
  end
end
