# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "A client for the MakeOS decentralized code collaboration network"
  homepage "https://makeos.org/"
  version "0.0.20"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/make-os/kit/releases/download/v0.0.20/kit_0.0.20_Darwin_x86_64.tar.gz"
    sha256 "b562659d4c53fe7f972ddf3b02cc686ed832eb39af9629b866f610bce15c332c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/make-os/kit/releases/download/v0.0.20/kit_0.0.20_Linux_x86_64.tar.gz"
    sha256 "8eeae9308ca713d092c84e802fac0e89ffe8103209139aaf968149158db4c8bf"
  end

  depends_on "git"

  def install
    bin.install "kit"
  end

  test do
    system "#{bin}/kit --version"
  end
end
