# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "A client for the MakeOS decentralized code collaboration network"
  homepage "https://makeos.org/"
  version "0.0.30"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/make-os/kit/releases/download/v0.0.30/kit_0.0.30_Darwin_x86_64.tar.gz"
    sha256 "1e325c3fa93f1cb83f3d1f83f019b1acb94391e9ebcd003c256bf3461354e8d9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/make-os/kit/releases/download/v0.0.30/kit_0.0.30_Linux_x86_64.tar.gz"
    sha256 "877c391962e0350fbfc3df689e05f816b16a0610f28d12f63f0633c0a1e04acc"
  end

  depends_on "git"

  def install
    bin.install "kit"
  end

  test do
    system "#{bin}/kit --version"
  end
end
