# This file was generated by GoReleaser. DO NOT EDIT.
class Lobe < Formula
  desc ""
  homepage "https://makeos.org/"
  version "0.0.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/make-os/lobe/releases/download/v0.0.17/lobe_0.0.17_Darwin_x86_64.tar.gz"
    sha256 "cad118bc9950a2963ad6af1ecece22dd78215a47903337d67a2e02d495b4490b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/make-os/lobe/releases/download/v0.0.17/lobe_0.0.17_Linux_x86_64.tar.gz"
      sha256 "39b115d2176bfa6a28f753619362e45ac2abeee8d8e49ffa112042f428788f68"
    end
  end
  
  depends_on "git"

  def install
    bin.install "lob"
  end

  test do
    system "#{bin}/lob --version"
  end
end
