# This file was generated by GoReleaser. DO NOT EDIT.
class Lobe < Formula
  desc ""
  homepage "https://makeos.org/"
  version "0.0.15"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/make-os/lobe/releases/download/v0.0.15/lobe_0.0.15_Darwin_x86_64.tar.gz"
    sha256 "1db4dbe8d2a2a8ab848b0a1dbe0d5291a45455c76e0e96475ed0f5510a90c5bf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/make-os/lobe/releases/download/v0.0.15/lobe_0.0.15_Linux_x86_64.tar.gz"
      sha256 "b3cb3a0573d6bdc9ffbec90d78aea699c1309efda7d8f958b07bd1ed14e5c0a0"
    end
  end
  
  depends_on "git"

  def install
    bin.install "lob"
  end

  test do
    system "#{bin}/lob --version"
  end
end
